name: Submit GoutSnap Sitemap URLs to IndexNow

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - dev
# on:
#   workflow_dispatch:  # Allow manual trigger from GitHub Actions UI or CLI.
#   schedule:
#     - cron: 0 0 1 * *  # Run at midnight UTC on the 1st day of each month.

permissions: read-all

jobs:
  test-submit-sitemaps-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --frozen

      - name: Submit URLs from single sitemap to IndexNow
        run: >
          uv run python src/helper/submit.py
          --host goutsnap.com
          --api-key ab3ff050879f49dba39bc5689fcd9109
          --api-key-location https://goutsnap.com/ab3ff050879f49dba39bc5689fcd9109.txt
          --endpoint bing
          --sitemap-locations https://goutsnap.com/sitemap.xml

      # - name: Submit multiple URLs to IndexNow
      #   run: >
      #     uv run python src/helper/submit.py
      #     --host goutsnap.com
      #     --api-key ab3ff050879f49dba39bc5689fcd9109
      #     --api-key-location https://goutsnap.com/ab3ff050879f49dba39bc5689fcd9109.txt
      #     --endpoint bing
      #     --sitemap-locations "
      #       https://goutsnap.com/sitemap-es.xml
      #       https://goutsnap.com/sitemap-vn.xml
      #       https://goutsnap.com/sitemap-ja.xml
      #       https://goutsnap.com/sitemap-ko.xml
      #       https://goutsnap.com/sitemap-ar.xml
      #       https://goutsnap.com/sitemap-zh.xml
      #       https://goutsnap.com/sitemap-pt.xml
      #       https://goutsnap.com/sitemap-de.xml
      #       https://goutsnap.com/sitemap-fr.xml
      #       https://goutsnap.com/sitemap-en.xml"
